Initial project setup
aeh1707/hello-microverse pull request #1
Opened 2022-04-20 15:04 UTC by aeh1707

2022-04-20 16:58 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @aeh170,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
>- [ ] I see that you added `test.md` to your `gitignore` file but still I can see it in your repo please fix that. You can try removing test.md from your `initial-project-setup` branch repo, then try to push your local git repo again.
>- [ ] Please kindly add a more descriptive PR title and description.
### Kindly Edit you PR as you have no PR Title or Description
> ![Screenshot from 2022-04-20 17-55-01](https://user-images.githubusercontent.com/52934128/164283426-ee3ff0a1-fd7d-4262-94ad-a9148c4d2d87.png)

> See an example in the video I made below on how to edit your PR 
 https://user-images.githubusercontent.com/52934128/164285366-615819f0-05d6-45af-8f13-886a04ec1ffd.mp4



> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-20 16:58 UTC, topeogunleye commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
- [x] [REQUIRED] I kindly suggest that you import your styles.css into your index.html so that your styles will be applied.
- [x] And please remember to use a class selector instead of an element selector to style your code as I stated in the comments below.

**EXAMPLE:**
Notice the highlighted piece of code:
![Screenshot from 2022-04-20 18-15-41](https://user-images.githubusercontent.com/52934128/164286635-ed3a5495-fb1d-4630-a22c-a4e1c63fba0f.png)

2022-04-20 16:58 UTC, topeogunleye commented on styles.css
> +h1 {
- [ ] [REQUIRED] You are using an element selector to style the heading, I kindly suggest using a class selector instead to follow the project requirements. You can add to class to the heading and use that class here to style the heading.

2022-04-20 16:58 UTC, topeogunleye commented on README.md
> +# Hello Microverse
- [ ] [Required] I kindly suggest that you add a description of the project underneath this section

**EXAMPLE**
```
# Hello Microverse
This is my first Microverse project
```

2022-04-20 16:58 UTC, topeogunleye commented on README.md
> +
- [ ] [REQUIRED] I kindly suggest you add steps to run the project locally:
```
### EXAMPLE
## Getting Started
To get a local copy up and running, follow the steps in Setup below.

### Setup
If you installed git you can clone the code to your machine, or download a ZIP of all the files directly.

[Download the ZIP from this location](https://github.com/aeh1707/hello-microverse/archive/refs/heads/main.zip), or run the following [git](https://git-scm.com/downloads) command to clone the files to your machine:

```bash
git clone https://github.com/aeh1707/hello-microverse.git
```

`- Once the files are on your machine, open the _hello-microverse_ folder in [Visual Studio Code](https://code.visualstudio.com/).`
```

- With the files open in Visual Studio Code, press the **Go Live** button at the bottom of the window to launch the files with [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).

2022-04-21 00:37 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 00:38 UTC, merged